### GET ALL TASKS
GET http://localhost:8080/api/tasks
Accept: application/json

### GET TASKS BY ID
GET http://localhost:8080/api/tasks/1
Accept: application/json

### GET TASKS BY ID NOT FOUND
GET http://localhost:8080/api/tasks/99999
Accept: application/json

### NEW TASKS
POST http://localhost:8080/api/tasks
Accept: application/json
Content-Type: application/json

{
  "title": "Self development",
  "description": "Reading 10 pages of a programming book",
  "due_date": "2024-01-10T00:00:00Z"
}

### NEW TASKS ERROR
POST http://localhost:8080/api/tasks
Accept: application/json
Content-Type: application/json

{
  "description": "Reading 10 pages of a programming book",
  "due_date": "2024-01-10T00:00:00Z"
}

### UPDATE TASKS 
PUT http://localhost:8080/api/tasks/1
Accept: application/json
Content-Type: application/json

{
  "title": "Programming",
  "description": "Reading 10 pages of a programming book",
  "due_date": "2024-01-10T00:00:00Z"
}

### UPDATE TASKS ERROR
PUT http://localhost:8080/api/tasks/1
Accept: application/json
Content-Type: application/json

{
  "description": "Handling Error BUg",
  "due_date": "2024-01-10T00:00:00Z"
}

### DELETE TASKS BY ID
DELETE http://localhost:8080/api/tasks/1
Accept: application/json

### DELETE TASKS BY ID NOT FOUND
DELETE http://localhost:8080/api/tasks/99999
Accept: application/json

### COMPLATED TASKS BY ID
PUT http://localhost:8080/api/tasks/2/status
Accept: application/json
Content-Type: application/json

{
  "is_completed": true
}

### COMPLATED TASKS BY ID ERROR
PUT http://localhost:8080/api/tasks/2/status
Accept: application/json
Content-Type: application/json

{
  "completed": true
}