// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"net/http"
	"simple-to-do/app/api"
	"simple-to-do/app/repositories"
	"simple-to-do/app/usecases"
	"simple-to-do/config"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitializedApp() *http.Server {
	repositoriesRepositories := repositories.NewDatamaster()
	db := config.InitMysqlMasterData()
	validate := config.NewValidator()
	usecase := usecases.NewTodoUsecase(repositoriesRepositories, db, validate)
	rest := api.NewApi(usecase)
	server := config.InitHandler(rest)
	return server
}
