version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: datamaster
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"  # Mengekspos port 3306 dari host ke kontainer
    volumes:
      - mysql_data:/var/lib/mysql  # Membuat volume untuk menyimpan data MySQL

volumes:
  mysql_data:  # Nama volume untuk data persisten